import React from 'react';

export const screens = {
  Home: React.lazy(() => import('../features/home/screens/Home')),
  Explore: React.lazy(() => import('../features/home/screens/Explore')),
  Cocina: React.lazy(() => import('../features/recipes/screens/Cocina')),
  More: React.lazy(() => import('../features/home/screens/More')),
  RecipeDetail: React.lazy(() => import('../features/recipes/screens/RecipeDetail')),
  AddMeal: React.lazy(() => import('../features/food/screens/AddMeal')),
  AddTolerance: React.lazy(() => import('../features/wellness/screens/AddTolerance')),
  DailyCheckIn: React.lazy(() => import('../features/wellness/screens/DailyCheckIn')),
  CreateRecipe: React.lazy(() => import('../features/recipes/screens/CreateRecipe')),
  CreatePost: React.lazy(() => import('../features/social/screens/CreatePost')),
  AICoach: React.lazy(() => import('../features/ai/screens/AICoach')),
  RealFeelDiary: React.lazy(() => import('../features/wellness/screens/RealFeelDiary')),
  FastingTimer: React.lazy(() => import('../features/wellness/screens/FastingTimer')),
  ImportRecipeURL: React.lazy(() => import('../features/recipes/screens/ImportRecipeURL')),
  Settings: React.lazy(() => import('../features/profile/screens/Settings')),
  Profile: React.lazy(() => import('../features/profile/screens/Profile')),
  Pantry: React.lazy(() => import('../features/planner/screens/Pantry')),
  WeeklyCheckIn: React.lazy(() => import('../features/wellness/screens/WeeklyCheckIn')),
  RialPlus: React.lazy(() => import('../features/profile/screens/RialPlus')),
  CreatorVerification: React.lazy(() => import('../features/social/screens/CreatorVerification')),
  CreatorDashboard: React.lazy(() => import('../features/social/screens/CreatorDashboard')),
  FoodDictionary: React.lazy(() => import('../features/food/screens/FoodDictionary')),
  Challenges: React.lazy(() => import('../features/social/screens/Challenges')),
  CreatorProfile: React.lazy(() => import('../features/social/screens/CreatorProfile')),
  PostDetail: React.lazy(() => import('../features/social/screens/PostDetail')),
  StoryViewer: React.lazy(() => import('../features/social/screens/StoryViewer')),
  CreateStory: React.lazy(() => import('../features/social/screens/CreateStory')),
  Notifications: React.lazy(() => import('../features/social/screens/Notifications')),
  ChallengeDetail: React.lazy(() => import('../features/social/screens/ChallengeDetail')),
  Progress: React.lazy(() => import('../features/wellness/screens/Progress')),
} as const;
